const meds = [
    { "name":"Tolbutamide" },
    { "name":"Glimepiride " },
    { "name":"Glipizide" },
    { "name":"Glyburide" },
    { "name":"Glyburide, micronized" },
    { "name":"Repaglinide " },
    { "name":"Nateglinide " },
    { "name":"Metformin" },
    { "name":"Acarbose " },
    { "name":"Pioglitazone" },
    { "name":"Rosiglitazone " },
    { "name":"Exenatide" },
    { "name":"Liraglutide  " },
    { "name":"Albiglutide  " },
    { "name":"Dulaglutide" },
    { "name":"Alogliptin" },
    { "name":"Sitagliptin  " },
    { "name":"Saxagliptin" },
    { "name":"Linagliptin" },
    { "name":"Canagliflozin" },
    { "name":"Dapagliflozin" },
    { "name":"Empagliflozin" }
]